### ISSUE TITLE
Broken by Home Assistant Core 2023.5

### ISSUE THREAD

**Issue by MichaelB2018** [akhudek/legrand_rflc#2]
This integration was broken by Home Assistant Core 2023.5:

https://github.com/home-assistant/core/pull/91929

**Comment by akhudek** [comment]
Dang. Ok I'll find some time next week to take a look. I haven't updated to that version yet.

**Comment by MichaelB2018** [comment]
Thanks. I thought this was simply a task of changing __init__.py:

from

        hass.config_entries.async_setup_platforms(entry, PLATFORMS)

to

       hass.config_entries.async_forward_entry_setup(entry, PLATFORMS)

But although that does not give an error message anymore, it's not working either. So I didn't get any further than this yet

**Comment by MichaelB2018** [comment]
ah... got it... You need to change line 56 from 

        hass.config_entries.async_setup_platforms(entry, PLATFORMS)

to

        await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

and now it works again.

**Comment by akhudek** [comment]
Nice! Did you want to do a PR? Otherwise I'll try these fixes during the week. Thanks for figuring it out!

**Comment by MichaelB2018** [comment]
Sure - sent you a pull request. Thanks for creating this add-on!

**Comment by akhudek** [comment]
Works for me too! Thanks for the update. I can't take credit for creating the add-on, just packaging it as a custom component. :)

**Comment by apple-ihack-geek** [comment]
This works for me as well, glad you fixed it.  Let me know if you guys have any questions.
