### ISSUE TITLE
Deprecated Supported Features

### ISSUE THREAD

**Issue by meanaverage** [akhudek/legrand_rflc#5]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1319
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 12:07:53 AM (19 occurrences)
Last logged: 12:07:53 AM

Entity None (<class 'custom_components.legrand_rflc.light._Dimmer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.TRANSITION: 32> and color modes, please report it to the author of the 'legrand_rflc' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by akhudek** [comment]
Thanks for letting me know. I'll take a look this week.

**Comment by meanaverage** [comment]
Thank you. I ran it through gpt 4o and it updated my local code to the new
standard. We're living in the future.

Really appreciate your hard work, despite our new robot overlords.

**Comment by akhudek** [comment]
Ok, this is fixed!
